<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <TrimUnusedDependencies>false</TrimUnusedDependencies>

    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>

    <StartupObject>SentroFPS.Launcher.Program</StartupObject>

    <EnableWindowsTargeting>true</EnableWindowsTargeting>
  </PropertyGroup>

  <ItemGroup>
    <!-- Inclure tous les assets -->
    <Content Include="Assets\**" CopyToOutputDirectory="Always" />
  </ItemGroup>

</Project>

