name: Build SentroFPS Launcher

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore SentroFPS/launcher-wpf/SentroFPS.Launcher.csproj

      - name: Build launcher
        run: dotnet publish SentroFPS/launcher-wpf/SentroFPS.Launcher.csproj -c Release -r win-x64 -p:PublishSingleFile=true -p:TrimUnusedDependencies=false --self-contained true -o out

      - name: Rename executable
        run: |
          cd out
          ren *.exe SentroFPS.exe

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: SentroFPS
          path: out/SentroFPS.exe

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: SentroFPS
          path: out

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          body: "Automatic release for ${{ github.ref_name }}"
          files: out/SentroFPS.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
